# This is a basic workflow to showcase the use of Reusable Workflows

name: main

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  docker:
    uses: AshwiniRanganath2020/ReusableWorkflow/.github/workflows/build.yml@main
    with:
      image_name: ashwiniranganath2020/trivyscan
      tag: ashwiniranganath2020/trivyscan
    secrets:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
