name: master

on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Scripts

        run: |
          docker build -t trivynew .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag trivynew ashwiniranganath2020/trivynew
          docker push ashwiniranganath2020/trivynew
